version: '3.4'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "5001:80"
    depends_on:
    - api
    environment:
      API: "http://api:80"
 
  api:
    build: ./
    ports:
      - "5000:80"
    environment:
     ConnectionStrings__DefaultConnection: "Server=database;User Id=sa;Password=yourStrong(!)Password;Database=Challange;Encrypt=False"
     ConnectionStrings__CacheConnection: cache
    depends_on:
     - database
     - cache

  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    
  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
